In [1]:
import numpy as np
import pandas as pd
df=pd.read_csv('df_preg_hormone_drug_uniqueCD.csv')
df_age_birthdate=pd.read_csv('df_preg_age_birthdate2.csv')
df_smoke=pd.read_csv('df_preg_smoke2.csv')
print(df.shape)

(3628, 28)

In [2]:
df.describe(include='all')

,PATIENT_NUM,START_DATE,TVAL_CHAR,LANGUAGE_CD,RACE_CD,ZIP_CD,N_pos,N_neg,HDID:149,HDID:301,...,ICD9:628.8,ICD9:628.0,RXCUI:762001,ICD9:628.2,RXCUI:206101,INS:ZZINFERTILITY SVC,RXCUI:150840,ICD9:628.3,RXCUI:890918,ICD9:V26.21
count,3.628000e+03,3628,3628,3628,3628,3.628000e+03,3628.000000,3628.000000,3413,2568,...,216,169,3628,62,3628,47,3628,18,3628,21
unique,NaN,3628,2,23,12,NaN,NaN,NaN,416,388,...,4,3,2,3,2,1,2,2,2,3
top,NaN,2013-01-26 13:54:20,neg,DEM|LANGUAGE:engl,DEM|RACE:black,NaN,NaN,NaN,4.3,3.5,...,PRIMARY,PRIMARY,False,PRIMARY,False,PRIMARY,False,SECONDARY,False,PROBLEM
freq,NaN,1,3203,2717,2082,NaN,NaN,NaN,70,36,...,85,85,3597,38,3614,47,3597,11,3614,16
mean,3.038554e+06,NaN,NaN,NaN,NaN,7.906125e+04,0.285832,2.720232,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,2.483524e+06,NaN,NaN,NaN,NaN,1.280418e+06,0.990803,4.092433,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,3.136000e+03,NaN,NaN,NaN,NaN,1.022000e+03,0.000000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.236242e+06,NaN,NaN,NaN,NaN,2.121000e+03,0.000000,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.207852e+06,NaN,NaN,NaN,NaN,2.126000e+03,0.000000,1.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,4.326422e+06,NaN,NaN,NaN,NaN,2.149000e+03,0.000000,3.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1.162520e+07,NaN,NaN,NaN,NaN,2.451000e+07,29.000000,38.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_age_birthdate.head()

   PATIENT_NUM  BIRTH_DATE  AGE_IN_YEARS_NUM
0         3136  1986-06-17                28
1         3808  1977-01-11                37
2         5502  1968-06-16                46
3         5817  1990-04-12                24
4         6965  1976-01-03                39

In [4]:
# df_age_birthdate.describe(include='all')
df=pd.merge(df,df_age_birthdate,on='PATIENT_NUM')
df=pd.merge(df,df_smoke,on='PATIENT_NUM')

# y

In [5]:
# w['female'] = w['female'].map({'female': 1, 'male': 0})
df['TVAL_CHAR'] = df['TVAL_CHAR'].map({'pos': 1, 'neg': -1})

# preg and infertility

In [6]:
# df['HDID:7177']=df['HDID:7177'].str.lower()
# df.loc[df['HDID:7177']=='positive;','HDID:7177']='pos'
# df.loc[df['HDID:7177'].isin(['not evalua','uncertain']),'HDID:7177']='neg'
# # df['HDID:7177'].value_counts().to_frame()

In [7]:
df['HDID:2578'] = df['HDID:2578'].map({'pos': 1, 'neg': -1})
df['HDID:50588'] = df['HDID:50588'].map({'pos': 1, 'neg': -1})
df['HDID:7177'] = df['HDID:7177'].map({'pos': 1, 'neg': -1})

# LANGUAGE_CDcode

In [8]:
print(df.LANGUAGE_CD.value_counts().to_frame().index[0:4])

df.loc[~df.LANGUAGE_CD.isin(df.LANGUAGE_CD.value_counts().to_frame().index[0:4]),'LANGUAGE_CD']='others'
# 
print(df.LANGUAGE_CD.value_counts().to_frame())

df.LANGUAGE_CD = pd.Categorical(df.LANGUAGE_CD)

# df.LANGUAGE_CD
print(dict( enumerate(df['LANGUAGE_CD'].cat.categories) ))

# df['LANGUAGE_CDcode'] = df.LANGUAGE_CD.cat.codes

# df['LANGUAGE_CDcode'].value_counts().to_frame()

Index([u'DEM|LANGUAGE:engl', u'DEM|LANGUAGE:creo', u'DEM|LANGUAGE:span',
       u'DEM|LANGUAGE:ccv'],
      dtype='object')
                   LANGUAGE_CD
DEM|LANGUAGE:engl         2717
DEM|LANGUAGE:creo          300
DEM|LANGUAGE:span          276
others                     237
DEM|LANGUAGE:ccv            98
{0: 'DEM|LANGUAGE:ccv', 1: 'DEM|LANGUAGE:creo', 2: 'DEM|LANGUAGE:engl', 3: 'DEM|LANGUAGE:span', 4: 'others'}

# RACE_CD

In [9]:
print(df.RACE_CD.value_counts().to_frame())#.index[0:4])

                       RACE_CD
DEM|RACE:black            2082
DEM|RACE:hispanic          583
DEM|RACE:c                 408
DEM|RACE:o                 282
DEM|RACE:asian              87
DEM|RACE:b                  74
DEM|RACE:m                  60
DEM|RACE:d                  24
DEM|RACE:@                  15
DEM|RACE:amer. indian        9
DEM|RACE:mr                  2
DEM|RACE:api                 2

In [10]:
df.loc[df.RACE_CD.isin(['DEM|RACE:b']),'RACE_CD']='DEM|RACE:black'
df.loc[df.RACE_CD.isin(['DEM|RACE:mr']),'RACE_CD']='DEM|RACE:m'

In [11]:
# print(df.RACE_CD.value_counts().to_frame())

In [12]:
df.loc[~df.RACE_CD.isin(df.RACE_CD.value_counts().to_frame().index[0:6]),'RACE_CD']='DEM|RACE:o'

In [13]:
print(df.RACE_CD.value_counts().to_frame())
# df.RACE_CD = pd.Categorical(df.RACE_CD)
# print(dict( enumerate(df['RACE_CD'].cat.categories) ))
# df['RACE_CDcode'] = df.RACE_CD.cat.codes

                   RACE_CD
DEM|RACE:black        2156
DEM|RACE:hispanic      583
DEM|RACE:c             408
DEM|RACE:o             332
DEM|RACE:asian          87
DEM|RACE:m              62

# ZIP_CD

In [14]:
# print(df.ZIP_CD.value_counts().to_frame())

# ICD9:628.9 	SVC:BMC:OB/GYN-FAMILY PLANNING 	ICD9:628.8 	ICD9:628.0

In [15]:
# print(df['ICD9:628.9'].value_counts().to_frame())
# df['ICD9:628.9'] = pd.Categorical(df['ICD9:628.9'])
# print(dict( enumerate(df['ICD9:628.9'].cat.categories) ))
# df['ICD9:628.9code'] = df['ICD9:628.9'].cat.codes

# print(df['ICD9:628.0'].value_counts().to_frame())
# df['ICD9:628.0'] = pd.Categorical(df['ICD9:628.0'])
# print(dict( enumerate(df['ICD9:628.0'].cat.categories) ))
# df['ICD9:628.0code'] = df['ICD9:628.0'].cat.codes

# print(df['ICD9:628.8'].value_counts().to_frame())
# df['ICD9:628.8'] = pd.Categorical(df['ICD9:628.8'])
# print(dict( enumerate(df['ICD9:628.8'].cat.categories) ))
# df['ICD9:628.8code'] = df['ICD9:628.8'].cat.codes

# # df.columns
# df['ICD9:628.0code'].unique()

In [16]:
df.loc[df['SVC:BMC:OB/GYN-FAMILY PLANNING'].isin(df['SVC:BMC:OB/GYN-FAMILY PLANNING'].value_counts().to_frame().index[1:5]),'SVC:BMC:OB/GYN-FAMILY PLANNING']='BMC-H FAMILY PLANNING-H FAMILY PLANNING'
print(df['SVC:BMC:OB/GYN-FAMILY PLANNING'].value_counts().to_frame())
# df['SVC:BMC:OB/GYN-FAMILY PLANNING'] = pd.Categorical(df['SVC:BMC:OB/GYN-FAMILY PLANNING'])
# print(dict( enumerate(df['SVC:BMC:OB/GYN-FAMILY PLANNING'].cat.categories) ))
# df['SVC:BMC:OB/GYN-FAMILY PLANNINGcode'] = df['SVC:BMC:OB/GYN-FAMILY PLANNING'].cat.codes

                                         SVC:BMC:OB/GYN-FAMILY PLANNING
BMC-H FAMILY PLANNING-H FAMILY PLANNING                              92

# HDID:149 	HDID:301 HDID:292

In [17]:
# df['HDID:149'].unique()

# df[df['HDID:149']=='LESS THAN 0.3  FSH']
# df['HDID:149'].str.extract(r'(\d)$').unique() #.str.extract 

df.loc[df['HDID:149']=='LESS THAN 0.3  FSH','HDID:149']='0.3'
df.loc[df['HDID:149']=='LESS THAN 0.3 MIU/M','HDID:149']='0.3'
df.loc[df['HDID:149']=='LESS THAN 0.1  FSH','HDID:149']='0.1'


# df[['HDID:149']]=df[['HDID:149']].convert_objects(convert_numeric=True)#.unique()

# df.loc[df['HDID:149'].str.isnumeric(),'HDID:149']
# df['HDID:149'].str.isnumeric()#.value_counts().to_frame()

In [18]:
df['HDID:149']=pd.to_numeric(df['HDID:149'])

In [19]:
# df['HDID:149']

In [20]:
# df['HDID:301'].unique()
df.loc[df['HDID:301']=='LESS THAN 0.1  LH R','HDID:301']='0.1'
df.loc[df['HDID:301']=='LESS THAN 0.1 MIU/M','HDID:301']='0.1'

In [21]:
# df[['HDID:301']]=df[['HDID:301']].convert_objects(convert_numeric=True)
df['HDID:301']=pd.to_numeric(df['HDID:301'])

In [22]:

df.loc[df['HDID:292']=='LESS THAN 0.1  FEMA','HDID:292']='0.1'
df.loc[df['HDID:292']=='QUANTITY N','HDID:292']=''

In [23]:
# df['HDID:292'].unique()
df['HDID:292']=pd.to_numeric(df['HDID:292'])

# to be done

In [24]:
df['HDID:3232'].unique()

array([nan, '10 (?)', 'REPORT  (N', '105.0', '113.0', '800.0',
       'LESS THAN 8    (NOT', '139.7', '100.0', '171.0', '237 (?)', '24.1',
       '55.0', '228.0', '12900.0', '39.7', '16 (?)', '7100.0', '4400.0',
       '21 (?)', '121.7', '62.0', '270.0', 'LESS THAN 8  Unit:', '25.0',
       '86.9', '30 (?)', '22 (?)', '13 (?)', '656.0', '39.0', '43.0',
       '59.0', '34 (?)', '148.0', '86 (?)', '103.0', '87 (?)', '105 (?)',
       '51 (?)', '232.0', '154.0', '50.0', '175.0', '15 (?)', '28.2',
       '45.0', '69.0', '124.0', '41 (?)', '92.4', '29.0', '27.0', '49.0',
       '136.0', '2200.0', '24 (?)', '200.0', '5900.0', '99.6', '67 (?)',
       '67.0', '111 (?)', '135.0', '78.0', '250.0', '20.0', '94.0',
       '354.0', '35.0', '145 (?)', '9 (?)', '376.0', '51.0', '46 (?)',
       '84.0', '323.0', '253.7', '49 (?)', '168.0', '108 (?)', '210.0',
       '31 (?)', '116.0', '259 (?)', '32.0', '71.0', '151 (?)', '346.0',
       '83.0', '146.0', '162.0', '53.0', 'CANCELLED;', '156.0', '102 (?)',
       '52.0', '6700.0', '5000.0', '4500.0', '122.0', '125.0', '77.0',
       '160.4', '67.6', '15000.0', '617.0', '95 (?)', '167.0', '58 (?)',
       '79 (?)', '124.7', '14 (?)', '64 (?)', '42 (?)', '76.0', '95.1',
       '49.8', '130 (?)', '90.0', '722.0', '47 (?)', '41.0', '44 (?)',
       '53.5', '3200.0', '56.0', '91.0', '33 (?)', '61.0', '585 (?)',
       '15.0', '89.3', '219.0', '82 (?)', '5700.0', '3900.0', '43 (?)',
       '26 (?)', '489.0', '97.5', '8 (?)', '66.0', '84 (?)', '28.0',
       '23 (?)', '114 (?)', '87.0', '54.0', '193 (?)', '2700.0', '33.0',
       '96 (?)', '99 (?)', '19.0', '19 (?)', '26.0', '11500.0', '159 (?)',
       '92.0', '69 (?)', '16.0', '55 (?)', '10100.0', '22.0', '10.0',
       '129.0', '27 (?)', '534.0', '64.0', '42.0', '63 (?)', '191.0',
       '20 (?)', '59 (?)', '122 (?)', '36 (?)', '48 (?)', '303 (?)',
       '101 (?)', '38 (?)', '45 (?)', '98 (?)', '32 (?)', '196 (?)',
       '23.0', '110 (?)', '126 (?)', '246 (?)', '54 (?)', '25 (?)',
       '66 (?)', '61 (?)', '137 (?)', '62 (?)', '80 (?)'], dtype=object)

In [25]:
# pd.to_numeric(df['HDID:3232'])
df=df.rename(index=str, columns={"TVAL_CHAR": "y_preg"})

# age

In [26]:
df['START_DATE'] = pd.to_datetime(df['START_DATE'])
df['BIRTH_DATE'] = pd.to_datetime(df['BIRTH_DATE'])

In [27]:
df['AGE_Y']=(df['START_DATE'] -df['BIRTH_DATE'] ).dt.days/365

In [28]:
df.describe()#include='all'

,PATIENT_NUM,y_preg,ZIP_CD,N_pos,N_neg,HDID:149,HDID:301,HDID:2578,HDID:292,HDID:50588,HDID:7177,AGE_IN_YEARS_NUM,CLIN:CurrentCigaretteUse-NO,CLIN:EverCigaretteUser-YES,CLIN:CurrentCigaretteUse-YES,CLIN:PassiveCigaretteExposure-NO,CLIN:PassiveCigaretteExposure-YES,AGE_Y
count,3.628000e+03,3628.000000,3.628000e+03,3628.000000,3628.000000,3413.000000,2568.000000,2395.000000,702.000000,170.000000,368.000000,3628.000000,3628.000000,3628.000000,3628.000000,3628.000000,3628.000000,3628.000000
mean,3.038554e+06,-0.765711,7.906125e+04,0.285832,2.720232,9.214064,10.463357,-0.789562,9.694872,-0.588235,-0.750000,37.392778,0.856395,0.339305,0.275910,0.222437,0.050992,33.513523
std,2.483524e+06,0.643273,1.280418e+06,0.990803,4.092433,14.932090,11.965779,0.613799,14.210762,0.811079,0.662338,10.761357,0.350737,0.473539,0.447033,0.415940,0.220012,10.275155
min,3.136000e+03,-1.000000,1.022000e+03,0.000000,0.000000,0.100000,0.100000,-1.000000,0.100000,-1.000000,-1.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.068493
25%,1.236242e+06,-1.000000,2.121000e+03,0.000000,0.000000,3.600000,3.700000,-1.000000,0.800000,-1.000000,-1.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,25.040411
50%,2.207852e+06,-1.000000,2.126000e+03,0.000000,1.000000,5.100000,7.100000,-1.000000,4.700000,-1.000000,-1.000000,37.000000,1.000000,0.000000,0.000000,0.000000,0.000000,33.053425
75%,4.326422e+06,-1.000000,2.149000e+03,0.000000,3.000000,7.100000,12.800000,-1.000000,14.100000,-1.000000,-1.000000,45.000000,1.000000,1.000000,1.000000,0.000000,0.000000,41.465068
max,1.162520e+07,1.000000,2.451000e+07,29.000000,38.000000,165.000000,169.900000,1.000000,143.500000,1.000000,1.000000,80.000000,1.000000,1.000000,1.000000,1.000000,1.000000,77.495890

In [29]:
print(df.columns)
# df.dtypes

Index([u'PATIENT_NUM', u'START_DATE', u'y_preg', u'LANGUAGE_CD', u'RACE_CD',
       u'ZIP_CD', u'N_pos', u'N_neg', u'HDID:149', u'HDID:301', u'HDID:2578',
       u'HDID:292', u'RXCUI:688242', u'HDID:50588', u'HDID:3232',
       u'ICD9:628.9', u'HDID:7177', u'SVC:BMC:OB/GYN-FAMILY PLANNING',
       u'ICD9:628.8', u'ICD9:628.0', u'RXCUI:762001', u'ICD9:628.2',
       u'RXCUI:206101', u'INS:ZZINFERTILITY SVC', u'RXCUI:150840',
       u'ICD9:628.3', u'RXCUI:890918', u'ICD9:V26.21', u'BIRTH_DATE',
       u'AGE_IN_YEARS_NUM', u'CLIN:CurrentCigaretteUse-NO',
       u'CLIN:EverCigaretteUser-YES', u'CLIN:CurrentCigaretteUse-YES',
       u'CLIN:PassiveCigaretteExposure-NO',
       u'CLIN:PassiveCigaretteExposure-YES', u'AGE_Y'],
      dtype='object')

In [30]:
# for col in df:
#     print df[col].value_counts(dropna=False)

# Working with missing data

In [31]:
# df2=df[[ u'y_preg', u'LANGUAGE_CD', u'RACE_CD',u'ZIP_CD',u'N_pos', u'N_neg', u'HDID:149', u'HDID:301', u'HDID:2578', u'HDID:292',
#        u'HDID:7177', u'HDID:50588', 
#        u'LANGUAGE_CDcode', u'RACE_CDcode', u'ICD9:628.9code',
#        u'ICD9:628.0code', u'ICD9:628.8code',
#        u'SVC:BMC:OB/GYN-FAMILY PLANNINGcode', u'AGE_IN_YEARS_NUM', u'AGE_Y']]#u'HDID:3232',
# df2.fillna(0)
df2=df
df2=df2.drop([u'PATIENT_NUM', u'START_DATE', u'HDID:3232'], axis=1)

In [35]:
# df2.loc[df2.loc[:, 'HDID:149' ].isnull(),:]

In [148]:
# # Fill missing values of HDID:149 with the median of HDID:149 (median)
# df2.loc[:, 'HDID:149' ] =df2.loc[:, 'HDID:149' ].fillna( df2.loc[:, 'HDID:149' ].median() )
# df2.loc[:, 'HDID:301' ] =df2.loc[:, 'HDID:301' ].fillna( df2.loc[:, 'HDID:301' ].median() )
# df2.loc[:, 'HDID:292' ] =df2.loc[:, 'HDID:292' ].fillna( df2.loc[:, 'HDID:292' ].median() )

In [149]:
df2

,y_preg,LANGUAGE_CD,RACE_CD,ZIP_CD,N_pos,N_neg,HDID:149,HDID:301,HDID:2578,HDID:292,...,RXCUI:890918,ICD9:V26.21,BIRTH_DATE,AGE_IN_YEARS_NUM,CLIN:CurrentCigaretteUse-NO,CLIN:EverCigaretteUser-YES,CLIN:CurrentCigaretteUse-YES,CLIN:PassiveCigaretteExposure-NO,CLIN:PassiveCigaretteExposure-YES,AGE_Y
0,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2126,1.0,2.0,1.9,1.4,1.0,4.7,...,False,NaN,1986-06-17,28,1,1,1,0,0,22.487671
1,1,DEM|LANGUAGE:engl,DEM|RACE:black,2130,0.0,1.0,1.1,3.5,-1.0,4.7,...,False,NaN,1977-01-11,37,0,1,1,0,0,29.189041
2,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2343,0.0,0.0,5.1,7.1,NaN,23.6,...,False,NaN,1968-06-16,46,1,0,0,1,0,39.926027
3,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2118,0.0,7.0,4.9,10.3,-1.0,4.7,...,False,NaN,1990-04-12,24,1,0,0,1,0,22.441096
4,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2124,0.0,0.0,78.4,7.1,NaN,4.7,...,False,NaN,1976-01-03,39,1,1,1,1,0,30.490411
5,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2122,0.0,0.0,8.3,7.1,NaN,4.7,...,False,NaN,1965-08-07,49,0,1,1,0,0,45.646575
6,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2125,0.0,2.0,6.2,3.7,-1.0,4.7,...,False,NaN,1981-06-20,33,1,1,0,0,0,31.257534
7,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2125,0.0,1.0,2.0,3.5,-1.0,4.7,...,False,NaN,1986-06-17,28,1,0,0,0,0,26.501370
8,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2121,0.0,2.0,6.2,7.1,-1.0,4.7,...,False,NaN,1965-05-09,49,1,0,0,0,0,48.410959
9,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2115,0.0,0.0,5.7,7.1,NaN,4.7,...,False,NaN,1980-10-07,34,0,0,0,0,0,24.761644
10,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2169,0.0,0.0,4.1,2.2,NaN,4.7,...,False,NaN,1963-10-13,51,0,1,1,0,1,40.391781
11,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2136,0.0,0.0,2.1,2.0,NaN,4.7,...,False,NaN,1961-03-31,53,1,1,1,0,0,49.021918
12,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2721,0.0,5.0,3.6,12.3,-1.0,4.7,...,False,NaN,1981-01-13,33,1,1,1,0,0,25.531507
13,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2119,0.0,1.0,5.0,7.0,-1.0,4.7,...,False,NaN,1962-08-05,52,1,0,0,0,0,47.589041
14,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2723,0.0,7.0,6.8,11.8,-1.0,4.7,...,False,NaN,1986-11-25,28,1,0,0,0,0,26.057534
15,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2118,0.0,1.0,0.3,7.1,-1.0,4.7,...,False,NaN,1982-05-14,32,1,1,1,0,0,31.265753
16,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2124,0.0,7.0,46.6,7.1,-1.0,4.7,...,False,NaN,1959-08-18,55,1,0,0,0,0,50.986301
17,-1,DEM|LANGUAGE:engl,DEM|RACE:hispanic,2026,0.0,6.0,3.9,12.6,-1.0,4.7,...,False,NaN,1986-08-03,28,0,0,0,0,0,17.271233
18,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2072,0.0,1.0,5.1,7.1,NaN,4.7,...,False,NaN,1962-09-10,52,1,0,0,0,0,50.904110
19,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2126,0.0,2.0,3.7,7.1,-1.0,4.7,...,False,NaN,1967-10-08,47,1,0,0,0,0,42.057534
20,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2124,0.0,1.0,6.8,3.3,-1.0,4.7,...,False,NaN,1964-12-20,49,1,1,0,0,0,43.917808
21,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2126,0.0,2.0,3.6,7.1,-1.0,0.9,...,False,NaN,1970-05-20,44,1,0,0,0,0,39.983562
22,-1,DEM|LANGUAGE:creo,DEM|RACE:o,2301,0.0,2.0,4.0,4.1,-1.0,4.7,...,False,NaN,1976-04-20,38,1,0,0,1,0,27.194521
23,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2121,0.0,3.0,2.7,2.6,-1.0,4.7,...,False,NaN,1967-11-21,47,1,1,1,0,0,45.068493
24,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2122,1.0,22.0,5.8,7.6,-1.0,4.7,...,False,NaN,1985-11-10,29,0,1,1,0,0,28.391781
25,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2169,0.0,2.0,7.8,22.4,-1.0,4.7,...,False,NaN,1978-01-28,36,1,0,0,0,0,31.772603
26,-1,DEM|LANGUAGE:engl,DEM|RACE:hispanic,2122,0.0,0.0,3.8,5.9,NaN,4.7,...,False,NaN,1971-04-05,43,1,0,0,0,0,41.627397
27,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2119,0.0,0.0,8.3,6.0,NaN,4.7,...,False,NaN,1970-01-15,44,0,0,0,0,0,41.400000
28,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2122,0.0,3.0,2.3,2.8,-1.0,4.7,...,False,NaN,1986-03-06,28,0,1,1,0,0,24.753425
29,-1,DEM|LANGUAGE:creo,DEM|RACE:black,2126,2.0,4.0,1.6,4.4,-1.0,4.7,...,False,NaN,1978-06-05,36,1,1,1,0,0,34.465753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3598,-1,DEM|LANGUAGE:engl,DEM|RACE:o,2121,0.0,3.0,13.7,26.9,-1.0,4.7,...,False,NaN,1998-01-01,16,1,0,0,0,0,16.117808
3599,-1,others,DEM|RACE:o,2131,0.0,0.0,5.1,4.9,NaN,4.7,...,False,NaN,1980-06-04,34,1,0,0,0,0,32.895890
3600,-1,DEM|LANGUAGE:creo,DEM|RACE:black,2121,0.0,3.0,7.6,4.3,-1.0,4.7,...,False,NaN,1998-03-01,16,1,0,0,0,0,16.030137
3601,-1,others,DEM|RACE:black,2118,0.0,1.0,5.5,11.5,-1.0,0.1,...,False,NaN,1979-02-06,35,1,0,0,0,0,34.610959
3602,-1,DEM|LANGUAGE:engl,DEM|RACE:o,2301,0.0,1.0,3.5,7.1,-1.0,4.7,...,False,NaN,1992-08-22,22,1,0,0,0,0,20.728767
3603,-1,DEM|LANGUAGE:engl,DEM|RACE:black,1905,0.0,0.0,13.4,7.1,NaN,4.7,...,False,NaN,1969-10-08,45,1,0,0,0,0,43.660274
3604,-1,others,DEM|RACE:m,2151,0.0,1.0,41.0,7.1,-1.0,4.7,...,False,NaN,1964-03-22,50,1,0,0,0,0,49.002740
3605,-1,others,DEM|RACE:black,2140,0.0,1.0,2.5,4.6,-1.0,0.2,...,False,NaN,1988-03-12,26,1,0,0,0,0,26.008219
3606,-1,DEM|LANGUAGE:span,DEM|RACE:hispanic,3064,0.0,0.0,5.0,7.2,NaN,0.2,...,False,NaN,1990-03-25,24,1,1,0,0,0,23.846575
3607,-1,DEM|LANGUAGE:engl,DEM|RACE:c,2116,0.0,0.0,5.7,7.1,NaN,0.2,...,False,NaN,1979-10-07,35,1,1,1,0,0,33.597260
3608,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2136,0.0,0.0,5.6,7.1,NaN,4.7,...,False,NaN,1985-09-07,29,1,0,0,0,0,28.413699
3609,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2121,0.0,0.0,4.2,2.6,NaN,4.7,...,False,NaN,1979-12-24,35,1,0,0,0,0,33.701370
3610,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2118,0.0,2.0,6.4,14.0,-1.0,4.7,...,False,NaN,1996-01-16,18,1,0,0,0,0,18.178082
3611,-1,DEM|LANGUAGE:span,DEM|RACE:hispanic,2453,0.0,12.0,5.6,7.1,-1.0,4.7,...,False,NaN,1994-12-14,20,1,0,0,0,0,19.175342
3612,-1,DEM|LANGUAGE:engl,DEM|RACE:c,2119,0.0,1.0,10.1,11.5,-1.0,4.7,...,False,NaN,1973-11-05,41,1,0,0,0,0,39.835616
3613,-1,DEM|LANGUAGE:engl,DEM|RACE:hispanic,1841,0.0,1.0,3.9,11.1,-1.0,4.7,...,False,NaN,1996-06-04,18,1,0,0,0,0,17.375342
3614,-1,others,DEM|RACE:c,2151,0.0,0.0,6.6,7.1,NaN,4.7,...,False,NaN,1986-12-08,28,1,0,0,0,0,26.775342
3615,-1,others,DEM|RACE:o,2145,0.0,0.0,4.9,14.1,NaN,4.7,...,False,NaN,1987-10-24,27,1,0,0,0,0,25.610959
3616,-1,DEM|LANGUAGE:engl,DEM|RACE:asian,2145,0.0,1.0,3.1,10.2,-1.0,4.7,...,False,NaN,1982-01-02,32,1,0,0,0,0,31.884932
3617,-1,DEM|LANGUAGE:ccv,DEM|RACE:o,2125,0.0,2.0,4.3,7.1,-1.0,4.7,...,False,NaN,1995-10-20,19,1,0,0,1,0,18.268493
3618,1,DEM|LANGUAGE:span,DEM|RACE:hispanic,2119,0.0,1.0,4.8,1.8,-1.0,4.7,...,False,NaN,1989-04-18,25,1,1,0,0,0,24.906849
3619,-1,DEM|LANGUAGE:creo,DEM|RACE:black,2136,0.0,1.0,7.1,8.1,-1.0,4.7,...,False,NaN,1984-02-05,30,1,0,0,0,0,30.013699
3620,-1,DEM|LANGUAGE:span,DEM|RACE:o,2150,0.0,1.0,4.8,7.2,-1.0,4.7,...,False,NaN,1997-02-20,17,1,0,0,0,0,16.926027
3621,1,others,DEM|RACE:m,2119,0.0,0.0,3.3,3.2,NaN,4.7,...,False,NaN,1991-07-31,23,1,0,0,0,0,22.326027
3622,-1,DEM|LANGUAGE:engl,DEM|RACE:c,2721,0.0,1.0,7.6,7.1,-1.0,4.7,...,False,NaN,1987-01-24,27,1,1,1,0,0,27.139726
3623,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2139,0.0,0.0,6.4,4.4,NaN,4.7,...,False,NaN,1991-03-13,23,1,0,0,0,0,23.038356
3624,-1,DEM|LANGUAGE:span,DEM|RACE:hispanic,2136,0.0,1.0,32.1,25.1,-1.0,4.7,...,False,NaN,1975-05-10,39,1,0,0,0,0,38.687671
3625,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2119,0.0,0.0,4.3,7.1,NaN,4.7,...,False,NaN,1993-03-09,21,1,0,0,0,0,21.060274
3626,-1,DEM|LANGUAGE:engl,DEM|RACE:c,2568,0.0,0.0,6.8,7.7,NaN,4.7,...,False,NaN,1989-09-15,25,1,0,0,0,0,24.643836
3627,-1,DEM|LANGUAGE:engl,DEM|RACE:black,2121,0.0,2.0,5.1,7.1,-1.0,4.7,...,False,NaN,1994-11-06,20,1,0,0,0,0,19.416438

In [150]:
# Fill missing values of binary HDID:2578,HDID:7177, HDID:50588 with 0
# df2.fillna(0, inplace=True)

In [36]:
df2.describe()

,y_preg,ZIP_CD,N_pos,N_neg,HDID:149,HDID:301,HDID:2578,HDID:292,HDID:50588,HDID:7177,AGE_IN_YEARS_NUM,CLIN:CurrentCigaretteUse-NO,CLIN:EverCigaretteUser-YES,CLIN:CurrentCigaretteUse-YES,CLIN:PassiveCigaretteExposure-NO,CLIN:PassiveCigaretteExposure-YES,AGE_Y
count,3628.000000,3.628000e+03,3628.000000,3628.000000,3413.000000,2568.000000,2395.000000,702.000000,170.000000,368.000000,3628.000000,3628.000000,3628.000000,3628.000000,3628.000000,3628.000000,3628.000000
mean,-0.765711,7.906125e+04,0.285832,2.720232,9.214064,10.463357,-0.789562,9.694872,-0.588235,-0.750000,37.392778,0.856395,0.339305,0.275910,0.222437,0.050992,33.513523
std,0.643273,1.280418e+06,0.990803,4.092433,14.932090,11.965779,0.613799,14.210762,0.811079,0.662338,10.761357,0.350737,0.473539,0.447033,0.415940,0.220012,10.275155
min,-1.000000,1.022000e+03,0.000000,0.000000,0.100000,0.100000,-1.000000,0.100000,-1.000000,-1.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.068493
25%,-1.000000,2.121000e+03,0.000000,0.000000,3.600000,3.700000,-1.000000,0.800000,-1.000000,-1.000000,29.000000,1.000000,0.000000,0.000000,0.000000,0.000000,25.040411
50%,-1.000000,2.126000e+03,0.000000,1.000000,5.100000,7.100000,-1.000000,4.700000,-1.000000,-1.000000,37.000000,1.000000,0.000000,0.000000,0.000000,0.000000,33.053425
75%,-1.000000,2.149000e+03,0.000000,3.000000,7.100000,12.800000,-1.000000,14.100000,-1.000000,-1.000000,45.000000,1.000000,1.000000,1.000000,0.000000,0.000000,41.465068
max,1.000000,2.451000e+07,29.000000,38.000000,165.000000,169.900000,1.000000,143.500000,1.000000,1.000000,80.000000,1.000000,1.000000,1.000000,1.000000,1.000000,77.495890

In [39]:
df2.to_csv('df_preg_hormone_last_numeric3.csv', index=False)

In [37]:
df2.groupby('y_preg').mean()

,ZIP_CD,N_pos,N_neg,HDID:149,HDID:301,HDID:2578,HDID:292,RXCUI:688242,HDID:50588,HDID:7177,...,RXCUI:206101,RXCUI:150840,RXCUI:890918,AGE_IN_YEARS_NUM,CLIN:CurrentCigaretteUse-NO,CLIN:EverCigaretteUser-YES,CLIN:CurrentCigaretteUse-YES,CLIN:PassiveCigaretteExposure-NO,CLIN:PassiveCigaretteExposure-YES,AGE_Y
y_preg,,,,,,,,,,,,,,,,,,,,,
-1,68060.305963,0.268186,2.765220,9.669490,10.681110,-0.816737,9.385812,0.005308,-0.613333,-0.735974,...,0.003746,0.009054,0.003746,37.487043,0.848267,0.346238,0.282548,0.226350,0.054948,33.656628
1,161969.522353,0.418824,2.381176,5.694118,8.798316,-0.562500,11.240171,0.007059,-0.400000,-0.815385,...,0.004706,0.004706,0.004706,36.682353,0.917647,0.287059,0.225882,0.192941,0.021176,32.435017

In [38]:
df2.groupby('y_preg').median()

,ZIP_CD,N_pos,N_neg,HDID:149,HDID:301,HDID:2578,HDID:292,RXCUI:688242,HDID:50588,HDID:7177,...,RXCUI:206101,RXCUI:150840,RXCUI:890918,AGE_IN_YEARS_NUM,CLIN:CurrentCigaretteUse-NO,CLIN:EverCigaretteUser-YES,CLIN:CurrentCigaretteUse-YES,CLIN:PassiveCigaretteExposure-NO,CLIN:PassiveCigaretteExposure-YES,AGE_Y
y_preg,,,,,,,,,,,,,,,,,,,,,
-1,2126,0.0,1.0,5.2,7.1,-1.0,4.1,False,-1.0,-1.0,...,False,False,False,37,1,0,0,0,0,33.208219
1,2128,0.0,1.0,4.6,6.3,-1.0,8.2,False,-1.0,-1.0,...,False,False,False,37,1,0,0,0,0,32.679452